"""
<Short title of the analysis>

Reproducibility header (fill in / keep in sync with the report):
  Source file : <schema["source_file"]> (sheet: <schema["sheet"]>)
  Exported    : data/<name>.csv  (row_count in schema.json)
  Filters     : <schema["filters"]> (<schema["filter_combination"]>)
  Skills      : nanum-python-analysis, <other skills you followed>
  Seed        : <seed>

Rules (see skill://nanum-python-analysis): no network, no pip install, no raw rows in printed output
under the "summary only" data policy, results into the analysis folder only.
"""
from __future__ import annotations

import datetime as _dt
import json
import platform
from importlib import metadata as _md
from pathlib import Path

import numpy as np
import pandas as pd

NAME = "REPLACE_WITH_EXPORT_NAME"            # data/<NAME>.csv + data/<NAME>.schema.json
SKILLS = ["nanum-python-analysis"]           # add the skills you actually followed
SEED = 20260101
LABEL = (
    "**Python 분석 (앱 검증 범위 밖) / Python analysis (outside the app's validated tools)** — "
    "generated by a script in this folder; not covered by the app's validated statistics. Review before use."
)

ROOT = Path(".")                             # the analysis folder is the working directory
(ROOT / "figures").mkdir(exist_ok=True)
(ROOT / "tables").mkdir(exist_ok=True)


def load(name: str = NAME) -> tuple[pd.DataFrame, dict]:
    """Read the exported view and its schema. Never print the returned frame under 'summary only'."""
    csv_path = ROOT / "data" / f"{name}.csv"
    schema = json.loads((ROOT / "data" / f"{name}.schema.json").read_text(encoding="utf-8"))
    df = pd.read_csv(csv_path, encoding="utf-8")
    return df, schema


def package_versions(*modules: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for m in modules:
        try:
            out[m] = _md.version(m)
        except _md.PackageNotFoundError:
            out[m] = "not installed"
    return out


def repro_header(schema: dict, n_used: int, n_dropped: int = 0, *, packages: dict[str, str],
                 skills: list[str] = SKILLS, seed: int = SEED, notes: str = "") -> str:
    """Markdown reproducibility block for the top of the report."""
    filters = schema.get("filters") or []
    filt = "; ".join(
        " ".join(str(f.get(k)) for k in ("kind", "column", "text") if f.get(k)) for f in filters
    ) or "none"
    lines = [
        LABEL,
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Source file | {schema.get('source_file')} (sheet: {schema.get('sheet') or '-'}) |",
        f"| Exported | {schema.get('csv_file')} at {schema.get('exported_at')} |",
        f"| Rows in export / source total | {schema.get('row_count')} / {schema.get('source_total_rows')} |",
        f"| Rows analysed / dropped | {n_used} / {n_dropped} |",
        f"| Filters | {filt} ({schema.get('filter_combination')}) |",
        f"| Skills used | {', '.join(skills)} |",
        f"| Packages | {', '.join(f'{k} {v}' for k, v in packages.items())} |",
        f"| Python | {platform.python_version()} |",
        f"| Seed | {seed} |",
        f"| Run at | {_dt.datetime.now().astimezone().isoformat(timespec='seconds')} |",
    ]
    if notes:
        lines += ["", notes]
    return "\n".join(lines)


def write_report(name: str, title: str, header: str, body: str) -> Path:
    path = ROOT / f"{name}_report.md"
    path.write_text(f"# {title}\n\n{header}\n\n{body}\n", encoding="utf-8")
    return path


def small_cell_safe(n: int, minimum: int = 5) -> str:
    """Under 'summary only', do not print group summaries for groups smaller than `minimum`."""
    return "n<%d" % minimum if n < minimum else str(n)


if __name__ == "__main__":
    rng = np.random.default_rng(SEED)
    df, schema = load()
    n_before = len(df)
    # ... analysis here: print aggregates only ...
    # df = df.dropna(subset=[...]); n_dropped = n_before - len(df)
    header = repro_header(schema, n_used=len(df), n_dropped=n_before - len(df),
                          packages=package_versions("numpy", "pandas"))
    report = write_report(NAME, "Analysis title", header, "## Results\n\n(tables, figures, assumptions, limits)")
    print("report:", report)
