using System.Text;
using System.Text.Json;

namespace NanumCsvViewer.Agent.Python
{
    /// <summary>
    /// 결과 폴더에 omp가 Python 코드 진단을 쓰도록 설정을 쓴다:
    /// <c>.omp\lsp.json</c>(basedpyright·ruff의 절대 경로 실행 파일; pyright·pylsp·ty는 끔)과 루트 표지 <c>pyproject.toml</c>
    /// (omp는 작업 폴더에 rootMarkers 파일이 있어야 서버를 고른다; ruff의 표지는 pyproject.toml·ruff.toml이라 둘 다 만족시킨다).
    /// 이 앱이 만든 파일만 덮어쓴다(표지 문구로 구분): 사용자가 직접 만든 파일은 그대로 둔다.
    /// </summary>
    internal static class PythonLspConfig
    {
        /// <summary>lsp.json 최상위 "generatedBy" 값. omp는 servers 밖의 키를 무시한다.</summary>
        public const string GeneratedBy = "NanumCsvViewer";
        public const string PyProjectMarker = "# Generated by Nanum CSV Viewer";

        public static string LspJsonPath(string outputFolder) => Path.Combine(outputFolder, ".omp", "lsp.json");
        public static string PyProjectPath(string outputFolder) => Path.Combine(outputFolder, "pyproject.toml");

        /// <summary>lsp.json 본문. 모든 command는 절대 경로, 분석 인터프리터는 basedpyright의 python.pythonPath로 넘긴다.</summary>
        public static string BuildLspJson(string langServer, string ruff, string pythonPath)
        {
            using var ms = new MemoryStream();
            using (var w = new Utf8JsonWriter(ms, new JsonWriterOptions { Indented = true, Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping }))
            {
                w.WriteStartObject();
                w.WriteString("generatedBy", GeneratedBy);
                w.WriteStartObject("servers");

                w.WriteStartObject("basedpyright");
                w.WriteString("command", langServer);
                w.WriteStartArray("args"); w.WriteStringValue("--stdio"); w.WriteEndArray();
                w.WriteStartArray("fileTypes"); w.WriteStringValue(".py"); w.WriteStringValue(".pyi"); w.WriteEndArray();
                w.WriteStartArray("rootMarkers"); w.WriteStringValue("pyproject.toml"); w.WriteStringValue("pyrightconfig.json"); w.WriteEndArray();
                w.WriteStartObject("settings");
                w.WriteStartObject("python"); w.WriteString("pythonPath", pythonPath); w.WriteEndObject();
                w.WriteStartObject("basedpyright");
                w.WriteStartObject("analysis");
                w.WriteBoolean("autoSearchPaths", true);
                w.WriteString("diagnosticMode", "openFilesOnly");
                w.WriteBoolean("useLibraryCodeForTypes", true);
                w.WriteEndObject(); w.WriteEndObject(); w.WriteEndObject();
                w.WriteEndObject();

                w.WriteStartObject("ruff");
                w.WriteString("command", ruff);
                w.WriteStartArray("args"); w.WriteStringValue("server"); w.WriteEndArray();
                w.WriteStartArray("fileTypes"); w.WriteStringValue(".py"); w.WriteStringValue(".pyi"); w.WriteEndArray();
                w.WriteStartArray("rootMarkers"); w.WriteStringValue("pyproject.toml"); w.WriteStringValue("ruff.toml"); w.WriteStringValue(".ruff.toml"); w.WriteEndArray();
                w.WriteBoolean("isLinter", true);
                w.WriteEndObject();

                // 같은 일을 하는 다른 Python 서버가 PATH에 있어도 진단이 겹치지 않게 한다.
                foreach (string other in new[] { "pyright", "pylsp", "ty" })
                {
                    w.WriteStartObject(other);
                    w.WriteBoolean("disabled", true);
                    w.WriteEndObject();
                }

                w.WriteEndObject();
                w.WriteEndObject();
            }
            return Encoding.UTF8.GetString(ms.ToArray()) + "\n";
        }

        /// <summary>
        /// pyproject.toml 본문(진단 전용: 패키지 정의 없음). 분석 인터프리터가 venv(pyvenv.cfg가 있는 폴더의 Scripts\python.exe)이면
        /// pyright가 거기서 패키지를 찾도록 venvPath/venv도 쓴다. 시스템 Python이면 pythonPath 설정과 PATH 탐색에 맡긴다.
        /// </summary>
        public static string BuildPyProject(string pythonPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine(PyProjectMarker + ": settings for the Python code diagnostics of the analysis folder.");
            sb.AppendLine("# Safe to delete; the app recreates it. A file without this line is never overwritten.");
            sb.AppendLine("[tool.pyright]");
            sb.AppendLine("typeCheckingMode = \"basic\"");
            sb.AppendLine("reportMissingModuleSource = false");
            if (TryVenv(pythonPath, out string? venvPath, out string? venvName))
            {
                sb.AppendLine($"venvPath = '{venvPath}'");
                sb.AppendLine($"venv = '{venvName}'");
            }
            sb.AppendLine();
            sb.AppendLine("[tool.ruff]");
            sb.AppendLine("line-length = 100");
            return sb.ToString();
        }

        internal static bool TryVenv(string pythonPath, out string? venvPath, out string? venvName)
        {
            venvPath = venvName = null;
            try
            {
                string? scripts = Path.GetDirectoryName(pythonPath);
                string? venvDir = scripts == null ? null : Path.GetDirectoryName(scripts);
                if (venvDir == null || !File.Exists(Path.Combine(venvDir, "pyvenv.cfg"))) return false;
                if (!string.Equals(Path.GetFileName(scripts), "Scripts", StringComparison.OrdinalIgnoreCase)) return false;
                venvPath = Path.GetDirectoryName(venvDir);
                venvName = Path.GetFileName(venvDir);
                return !string.IsNullOrEmpty(venvPath) && !string.IsNullOrEmpty(venvName) && !venvPath.Contains('\'') && !venvName.Contains('\'');
            }
            catch (Exception) { return false; }
        }

        public sealed record WriteResult(bool LspWritten, bool ProjectWritten, bool LspKeptUserFile, bool ProjectKeptUserFile)
        {
            /// <summary>omp가 새로 읽어야 하는 변경이 있었는가(없으면 재시작 불필요).</summary>
            public bool Changed => LspWritten;
        }

        /// <summary>두 파일을 쓴다(내용이 같으면 건드리지 않는다). 이 앱이 만든 파일이 아니면 덮어쓰지 않는다. 쓰기 실패는 예외로 알린다.</summary>
        public static WriteResult Write(string outputFolder, string langServer, string ruff, string pythonPath)
        {
            Directory.CreateDirectory(Path.Combine(outputFolder, ".omp"));
            bool lspWritten = false, lspKept = false, projWritten = false, projKept = false;

            string lspPath = LspJsonPath(outputFolder);
            string lsp = BuildLspJson(langServer, ruff, pythonPath);
            if (File.Exists(lspPath))
            {
                string existing = File.ReadAllText(lspPath);
                if (existing == lsp) { /* 이미 최신 */ }
                else if (existing.Contains("\"generatedBy\"", StringComparison.Ordinal) && existing.Contains(GeneratedBy, StringComparison.Ordinal))
                { File.WriteAllText(lspPath, lsp, new UTF8Encoding(false)); lspWritten = true; }
                else lspKept = true;
            }
            else { File.WriteAllText(lspPath, lsp, new UTF8Encoding(false)); lspWritten = true; }

            string projPath = PyProjectPath(outputFolder);
            string proj = BuildPyProject(pythonPath);
            if (File.Exists(projPath))
            {
                string existing = File.ReadAllText(projPath);
                if (existing == proj) { }
                else if (existing.StartsWith(PyProjectMarker, StringComparison.Ordinal)) { File.WriteAllText(projPath, proj, new UTF8Encoding(false)); projWritten = true; }
                else projKept = true;
            }
            else { File.WriteAllText(projPath, proj, new UTF8Encoding(false)); projWritten = true; }

            return new WriteResult(lspWritten, projWritten, lspKept, projKept);
        }
    }
}
